/**
 * API barrel – re-exports from lib/api/index so `import { ... } from "@/lib/api"` works.
 * Giữ file này để resolver (Vite/TS) ưu tiên api.ts; nếu xóa thì "@/lib/api" trỏ vào thư mục api/.
 */
export {
  getAuthToken,
  AUTH_EXPIRED_EVENT,
  authFetch,
  getApiBase,
  handleApiError,
  fetchProducts,
  fetchPromotions,
  fetchCategories,
  fetchProductPackages,
  fetchVariantDetail,
  fetchProductInfo,
  checkPaymentHealth,
  createPayment,
  checkPaymentStatus,
  generateOrderId,
  createPaymentCodes,
  confirmBalancePayment,
  confirmTransfer,
  fetchUserProfile,
  fetchUserOrders,
  fetchUserTransactions,
  fetchUserReviews,
  updateProfile,
  changePassword,
  changeEmail,
  getSessions,
  revokeSession,
  getActivity,
  fetchFormFields,
  fetchTopupPackages,
  fetchTopupTransferCode,
  fetchCart,
  addToCart,
  updateCartItem,
  removeFromCart,
  clearCartApi,
  syncCart,
  getCartCount,
} from "./api/index";

export type {
  ProductDto,
  PromotionDto,
  ProductPackageDto,
  CategoryDto,
  VariantDetailDto,
  ProductInfoDto,
  CreatePaymentRequest,
  CreatePaymentResponse,
  PaymentStatusResponse,
  PaymentHealthResponse,
  ConfirmBalancePaymentItem,
  UserOrderItem,
  UserOrder,
  UserProfileDto,
  UserSessionDto,
  UserActivityLogDto,
  WalletTransactionDto,
  FormFieldDto,
  FormFieldsResponse,
  CartItemDto,
  CartResponse,
  CartAddResponse,
  CartCountResponse,
  VariantFullDataDto,
} from "./api/index";
