/**
 * API barrel – all client-side API and types.
 * Implementations live in lib/api/*.ts; this file keeps `import { ... } from "@/lib/api"` working.
 */
export {
  getAuthToken,
  AUTH_EXPIRED_EVENT,
  authFetch,
  fetchProducts,
  fetchPromotions,
  fetchCategories,
  fetchProductPackages,
  fetchVariantDetail,
  fetchProductInfo,
  checkPaymentHealth,
  createPayment,
  checkPaymentStatus,
  generateOrderId,
  confirmBalancePayment,
  fetchUserOrders,
  fetchFormFields,
  fetchCart,
  addToCart,
  updateCartItem,
  removeFromCart,
  clearCartApi,
  syncCart,
  getCartCount,
} from "./api/index";

export type {
  ProductDto,
  PromotionDto,
  ProductPackageDto,
  CategoryDto,
  VariantDetailDto,
  ProductInfoDto,
  CreatePaymentRequest,
  CreatePaymentResponse,
  PaymentStatusResponse,
  PaymentHealthResponse,
  ConfirmBalancePaymentItem,
  UserOrderItem,
  UserOrder,
  FormFieldDto,
  FormFieldsResponse,
  CartItemDto,
  CartResponse,
  CartAddResponse,
  CartCountResponse,
} from "./api/index";
